language: cpp
sudo: required
compiler:
- gcc
- clang
os:
- linux
- osx
osx_image: xcode8 # use 10.11
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install python bison flex libboost-dev libboost-filesystem-dev libboost-system-dev python ; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew install python bison flex && brew upgrade boost; fi
install:
- pip install --upgrade pip setuptools
- pip install requests[security]
- pip install pytest pyyaml
script:
- make all
- pushd erpcgen/test ; py.test ; popd
- python test/run_unit_tests.py
