language: cpp
sudo: required
dist: trusty
compiler:
- gcc
- clang
os:
- linux
- osx
osx_image: xcode8 # use 10.11
before_install:
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq; fi
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install python bison flex libboost-dev libboost-filesystem-dev libboost-system-dev python ; fi
- if [ $TRAVIS_OS_NAME == linux ]; then pyenv install 2.7.12 ; pyenv global 2.7.12; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
- if [ $TRAVIS_OS_NAME == osx ]; then brew install python bison flex && brew upgrade boost || true; fi
install:
#- sudo pip install --upgrade pip setuptools
#- CC=gcc sudo pip install requests[security]
- sudo pip install pytest
- sudo pip install pyyaml
- sudo pip install enum34
- sudo pip install pyserial
script:
- make all
- pushd erpcgen/test ; py.test ; popd
- python test/run_unit_tests.py
